### ISSUE TITLE
loop in malware url whitelisting only takes last item

### ISSUE THREAD

**Issue by richardjohnallsopp** [CiscoDevNet/ansible-meraki#195]
This very well might be me being crap, but I'm pretty sure this code should add a list of urls:
```
    # whitelist urls
    - name: if malware is enabled, set whitelisted urls
      meraki_malware:
        auth_key: "{{   auth_key  }}"
        org_name: "{{  org_name  }}"
        net_name: "{{  network_name  }}"
        state: present
        mode: "{{  enable_malware  }}"
        allowed_urls:
          - url: "{{  item.url  }}"
            comment: "{{  item.comment  }}"
      delegate_to: localhost
      with_items: "{{  whitelisted_urls  }}"
      when: malware.data.mode != "disabled"
      tags:
        - "malware"
```
var file
```
whitelisted_urls:
  - url: "www.google.co.uk"
    comment: "Google UK"
  - url: "www.google.com"
    comment: "Google US"
  - url: "www.yahoo.com"
    comment: "Yahoo US"
```
output
```
TASK [get malware settings] **********************************************************************************************************************************************
ok: [127.0.0.1 -> localhost]

TASK [if malware is enabled, set whitelisted urls] ***********************************************************************************************************************
changed: [127.0.0.1 -> localhost] => (item={'url': 'www.google.co.uk', 'comment': 'Google UK'})
changed: [127.0.0.1 -> localhost] => (item={'url': 'www.google.com', 'comment': 'Google US'})
changed: [127.0.0.1 -> localhost] => (item={'url': 'www.yahoo.com', 'comment': 'Yahoo US'})

PLAY RECAP ***************************************************************************************************************************************************************
127.0.0.1                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

![image](https://user-images.githubusercontent.com/50882889/94210299-3be40380-fec6-11ea-91e6-36e20829c509.png)
