### ISSUE TITLE
Module error on empty ruleset with meraki_mx_l7_firewall

### ISSUE THREAD

**Issue by mtb-xt** [CiscoDevNet/ansible-meraki#257]
Hi, this happens if the rules option contains an empty list:

```
        - name: Set L7 firewall rules
          meraki_mx_l7_firewall:
            org_name: "{{ org_name }}"
            net_name: "{{ item.name }}"
            state: present
            # rules: "{{ fw_global['mx_l7_firewall_rules'] + vars['fw_' + item.name|lower()]['mx_l7_firewall_rules']|default([]) }}"
            rules: []
          loop: "{{ networks }}"
          loop_control:
            label: "{{ item.name }}"
```

My use case is that for some networks, I do not define the rules, but for others I do, and I go over them with a loop.
I know this could be solved with a 'when' condition, but I think modules shouldn't throw module errors anyway...

```
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/hawara/.ansible/tmp/ansible-tmp-1632618514.9441214-22568-106472608179247/AnsiballZ_meraki_mx_l7_firewall.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/hawara/.ansible/tmp/ansible-tmp-1632618514.9441214-22568-106472608179247/AnsiballZ_meraki_mx_l7_firewall.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/hawara/.ansible/tmp/ansible-tmp-1632618514.9441214-22568-106472608179247/AnsiballZ_meraki_mx_l7_firewall.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.meraki.plugins.modules.meraki_mx_l7_firewall', init_globals=dict(_module_fqn='ansible_collections.cisco.meraki.plugins.modules.meraki_mx_l7_firewall', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_meraki_mx_l7_firewall_payload_7f_w62es/ansible_meraki_mx_l7_firewall_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_mx_l7_firewall.py\", line 479, in <module>\n  File \"/tmp/ansible_meraki_mx_l7_firewall_payload_7f_w62es/ansible_meraki_mx_l7_firewall_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_mx_l7_firewall.py\", line 448, in main\n  File \"/tmp/ansible_meraki_mx_l7_firewall_payload_7f_w62es/ansible_meraki_mx_l7_firewall_payload.zip/ansible_collections/cisco/meraki/plugins/modules/meraki_mx_l7_firewall.py\", line 331, in rename_id_to_appid\nKeyError: 'rules'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
```
