### ISSUE TITLE
Batch API support

### ISSUE THREAD

**Issue by mtb-xt** [CiscoDevNet/ansible-meraki#274]
Cisco Meraki API supports 'action batches' - https://developer.cisco.com/meraki/api-v1/#!action-batches-overview 

Would it be possible to integrate them with ansible meraki modules? At least per module, to save time on network requests in a switch ports loop for example?

If I have a playbook like this, as I understand, each loop element is a separate call to the API. With batching, it may be possible to prepare a batch change for switchport module, and then send them.
```
- name: Configure switch ports (this will take a long time)
  meraki_switchport:
    state: present
    serial: "{{ item.0.serial }}"
    number: "{{ item.1.port_id }}"
    enabled: "{{ item.1.enabled | bool | default(true) }}"
    name: "{{ item.1.name|default(omit) }}"
    tags: "{{ item.1.tags|default([]) }}"
    type: "{{ item.1.type }}"
    vlan: "{{ item.1.vlan }}"
    access_policy_number: "{{ item.1.access_policy_number | default(omit) }}"
    access_policy_type: "{{ item.1.access_policy_type | default(omit) }}"
    allowed_vlans: "{{ item.1.allowed_vlans | default('all') }}"
    isolation_enabled: "{{ item.1.isolation_enabled | default(omit) }}"
    link_negotiation: "{{ item.1.link_negotiation | default(omit) }}"
    poe_enabled: "{{ item.1.poe_enabled | default(false) }}"
    rstp_enabled: "{{ item.1.rstp_enabled | default('yes') }}"
    stp_guard: "{{ item.1.stp_guard | default('disabled') }}"
  loop: "{{ devices.switch | subelements('ports')  }}"
  loop_control:
    label: "{{ item.0.serial }}"
  tags: ["device", "switch", "ports"]
```

**Comment by kbreit** [comment]
I've considered Batch API but think it would be pretty hard to implement in Ansible without a significant amount of duplicate code in the modules. Reason being, Ansible requires you to declare your arguments. So I'd have a full set of normal arguments then a duplicate set for Batch API. Also, I'd only be implementing partial functionality since Batch API allows a single request hitting multiple endpoints. If you have a high level idea of what it would look like I'd welcome seeing it as the way I've thought about it isn't very feasible.

One option is a `meraki_raw` module which you can pass whatever data and endpoint you want and it would act as the transport. It wouldn't do parameter checking or anything, but would be flexible. It could also be a similar `meraki_batch_api` module which is similar but tailored to Batch API. Would either of these work?

**Comment by kbreit** [comment]
@mtb-xt I intended on working on this during the week but it didn't happen. This POC is still on my roadmap.

**Comment by kbreit** [comment]
@mtb-xt I started development on the module today and made some good progress. Documentation isn't complete and I'm building out the tests but the module framework is there. Once I'm content with this module framework I'll add templating support to the switchport module so it can feed the data structure into `meraki_batch_action`. See https://github.com/kbreit/ansible-meraki/tree/modules/actionbatch if you're curious what it looks like.

**Comment by craigers521** [comment]
Bump.  I'm also interested in action batch functionality for the ansible modules.  @kbreit is this still on the roadmap for you? That branch on your fork is listed as stale.  I like the direction so far, what do you think it needs to get it over the finish line?

**Comment by kbreit** [comment]
It's on the roadmap but somewhat down the list. To me batch actions feel awkward in Ansible but I understand there are situations it makes sense.

Current status is the module needs to be tested and documented but if I recall it's relatively close. The big work is going to be modifying other modules to output their payload. Do you have a module you'd like to use with action batches?

**Comment by craigers521** [comment]
Hey Good to hear.  I'd say offhand create/update networks, update switch
ports, create/update SSIDs would be some top contenders.

**Comment by kbreit** [comment]
@craigers521 I've come up with an approach on this module. I'm going to release it as is in a "beta" state. This will allow for public testing and feedback. I'm going to start working on adding support for `state: render_*` where `*` is a an Action Batch action. One place that'll likely catch you up is the modules will convert response data from camel case to snake case but the `body:` field will want camel case so I'll need to work on that. But expect a release with this module soon.

**Comment by craigers521** [comment]
Awesome.  I'll test it out and let you know. Thanks for the work on this.

**Comment by craigers521** [comment]
Hey Kevin - So I am coming back to this and ended up making some progress using some inline jinja.  This playbook will take my group/host vars for switchports that i can use normally with the ms_switchport module and creating a list of actions to send to the action_batch API.  Right now the only problem i ran into, i had to take the "number" out of the the payload as the AB was choking on this, so i'm just using the loop index as a replacement.  This makes the assumption obviously that all your switchports are defined in order with no gaps in between them.  

#### PLAYBOOK:
```
- name: test action batch builder
  hosts: dummy-sw1
  connection: local
  collections:
    - cisco.meraki
  tasks: 

  - name: set fact from jinja
    set_fact:
      batch_payload: >-
        [
        {% for port in switchports %}
          {"resource": "/devices/{{sn}}/switch/ports/{{loop.index}}", "operation": "update", "body": {{port}} }
          {% if not loop.last %},{% endif %}
        {% endfor %}
        ]

  - name: Configure switchports
    meraki_action_batch:
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      actions: "{{ batch_payload }}"
      synchronous: false
      confirmed: True
      state: present
    register: results

  - name: print result
    debug:
      msg: "{{ results }}"

  - name: get batch status
    meraki_action_batch:
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      action_batch_id: "{{ results['data']['id'] }}"
      state: query
    register: batch
    until: batch['data']['status']['completed'] == true
    retries: 5
    delay: 3

  - name: print batches status
    debug:
      msg: "Batch {{ batch['data']['id'] }} has status of {{ batch['data']['status'] }}"
```

#### group_vars
```
switchports:
  - name: WAN Trunk1
    type: trunk
    allowedVlans: "1,2,19-20,50"
  - name: WAN Trunk2
    type: trunk
    allowedVlans: "1,2,19-20,50"
  - name: LAN 3
    type: access
    vlan: 20
  - name: LAN 4
    type: access
    vlan: 20
    voiceVlan: 19
  - name: disabled port
    enabled: false
  - name: Guest
    vlan: 50
```
The serial is defined in host_vars.
