### ISSUE TITLE
Multiple tags not applying to devices.

### ISSUE THREAD

**Issue by TerriblePowershell** [CiscoDevNet/ansible-meraki#306]
When attempting to update the tags on devices, the devices will not take more than one tag when space delimited.

If tags are done in a list the device will take both tags without issue. 

```
  tags:
    - temp
    - recently-added
```

If tags are entered space delimited, the device retains it's previous tag(s).

```
  tags: temp recently-added
```

### Task for updating device information:

```
- name: Update information about a device.
  cisco.meraki.meraki_device:
    auth_key: "{{ auth }}"
    org_id: "{{ org }}"
    net_id: "{{ net_id }}"
    state: present
    serial: '{{ ap.ap_serial }}'
    name: "{{ ap.ap_name }}"
    address: "{{ ap.ap_address }}"
    tags: "{{ ap.ap_tags }}"
    move_map_marker: yes
  delegate_to: localhost
  loop: "{{ aps.list }}"
  loop_control: 
    loop_var: ap
```

### CSV file containing variables

```
ap_serial,ap_name,ap_address,ap_tags
1234-4568-9101,Jekyll,123 First Street,temp
5678-9210-1234,Hyde,456 Second Ave,temp recently-added
```

### File with variables for testing that isn't .csv

```
ap_serial: 1234-5678-9110
ap_name: gobbler-gobbler
ap_tags: recently-added temp
ap_address: "White House Drive"
```

**Comment by kbreit** [comment]
Thanks for reporting this. Let me look into this and get back to you.

**Comment by kbreit** [comment]
I believe this problem is actually with documentation instead of the code itself. IIRC, v0 of the API was space delimited and v1 is a list. I'll update documentation but my recommendation is to use a list. Is there a reason it needs to be space delimited?

**Comment by TerriblePowershell** [comment]
Ahh. That would explain why it isn't working. 

Not specifically, I suppose. I'm gearing up to swap out ~400-450 AP's here in the next month or two and was looking at using a .csv file for the AP's since it would be much easier to build out a .csv file with all the necessary parameters vs. doing it all in yaml. I figured it would be easier to use the tags if they were space delimited but I found a work-around for now. 

### Modified tags list in playbook.
```
…
    tags: 
      - "{{ ap.ap_tags1 }}"
      - "{{ ap.ap_tags2 }}"
      - "{{ ap.ap_tags3 }}"
…
```

### .csv headers
```
ap_serial,ap_name,ap_address,ap_tags1,ap_tags2,ap_tags3
```

The only issue I've found with this so far is that it does not remove tags if the field is blank.

**Comment by kbreit** [comment]
I'd like to clarify how you're trying to remove the tags. Are you specifying `tags:` like below?

```
tags:
  -
```

This would be an empty list. If you exclude `tags` altogether it wouldn't remove the tags. Just making sure.

**Comment by TerriblePowershell** [comment]
In order to remove the tags, I've just left that field of the .csv file blank. I thought that it might read it as an empty field and just remove the tag but it doesn't appear so. 

How it looks in the playbook:
```
    tags: 
      - "{{ ap.ap_tags1 }}"
      - "{{ ap.ap_tags2 }}"
      - "{{ ap.ap_tags3 }}"
```

The .csv file is written like this:
```
ap_serial,ap_name,ap_address,ap_tags1,ap_tags2,ap_tags3
1234-5678-9012,Jekyll,"123 Big Drive, Somewhere, USA",piglet,tommy,
```
Leaving the `ap_tags3` open doesn't seem to do anything but if I specify another tag in there, it will change all the tags.

**Comment by kbreit** [comment]
I get the feeling this is actually a problem related to Ansible and how it is importing it from the CSV. Do you have a full playbook to show this? I'd like to see how it's handling the CSV import.

**Comment by TerriblePowershell** [comment]
### Playbook: meraki-ap-update.yml:
```
---

- name: Rename new Meraki AP's
  hosts: ansible_hosts
  gather_facts: false
  vars: 
    old_netId: []
  
  pre_tasks:
    - name: read csv
      community.general.read_csv:
        path: "/etc/ansible/experimental/meraki_ap/ap_vars.csv"
        delimiter: ','
      register: aps

  roles:
    - { role: device-query, tags: ['query'] }
    - { role: rename-devices, tags: ['rename'] }
```

### Role device-query:
```
---

- name: Query device for network
  cisco.meraki.meraki_device:
    auth_key: "{{ auth }}"
    org_id: "{{ org }}"
    state: query
    serial: "{{ ap.ap_serial }}"
  delegate_to: localhost
  register: apinfo
  loop: "{{ aps.list }}"
  loop_control:
    loop_var: ap

# Uncomment for debugging apinfo output
# - name: debug apinfo
#   debug:
#     msg: "{{ apinfo.results }}"

- name: Create new variable from output
  set_fact:
    old_netId: |
      [
      {% for item in apinfo.results %}
        {
          "serial": "{{ item.data.serial }}",
          "network_id": "{{ item.data.network_id }}"
        },
      {% endfor %}
      ]
# - name: Check new variable
#   debug:
#     msg: "{{ old_netId }}"

- name: AP's listed here will need to be moved to the proper network.
  debug:
    msg: "{{ old_netId | selectattr('network_id','ne',net_id) | list }}"
```

### Role rename-devices:
```
---
