### ISSUE TITLE
meraki_ms_switchport trunk with no native vlan

### ISSUE THREAD

**Issue by The-Sec** [CiscoDevNet/ansible-meraki#425]
** PlaceHolder **

**Comment by y0rune** [comment]
For the creating the trunk port with the `native vlan` you can add `vlan` option in a playbook task:
Task:
```yaml
- name: Configure port as trunk
  meraki_switchport:
    auth_key: '{{ auth_key }}'
    state: present
    serial: '{{ serial_switch }}'
    number: 8
    enabled: true
    name: Test Port
    type: trunk
    vlan: 10
    allowed_vlans: 10, 100, 200
  delegate_to: localhost
```

After task screenshot from Meraki Dashboard:
![image](https://user-images.githubusercontent.com/10187235/213867296-3c566fae-4548-40b8-bf04-64cdbdc9913b.png)


That option is when the task has a `vlan`. In case when the option `vlan` is not in the playbook the port will have the previous value of the `vlan`.
