### ISSUE TITLE
meraki_device making wrong API call

### ISSUE THREAD

**Issue by victoreebel** [CiscoDevNet/ansible-meraki#463]
Trying the first example from the doc 'query all devices', substituting the dummy values for my own:

```
    - name: Query all devices in a network.
      cisco.meraki.meraki_device:
        auth_key: MYKEY
        org_name: MYORG
        net_name: MYNET
        state: query
      delegate_to: localhost
```

Might be missing something, but I'm getting this return -
`
 "msg": 404,                                                                                                                                                                                                                                  "response": "OK (unknown bytes)",                                                                                                                                                                                                            "status": 404,                                                                                                                                                                                                                               "url": "https://api.meraki.com/api/v1/organizations/<MY ORG ID>/configTemplates"  `
 
So it doesn't seem to be hitting the devices API, rather the configTemplates one.

 Module version is 2.15.3
